vkey: VERSION
versionsFile: classes/dreidel/vars
properties:
  com.jive.myco.jivewire : deps.jivewire.version
  com.jive.myco.jazz : deps.jazz.version
  jackson-extensions: deps.jackson-extensions.version
